AWSTemplateFormatVersion: "2010-09-09"

Description: Deploys CodeBuild resources

Parameters:
  GitRepository:
    Description: Git Repository.
    Type: String
    Default: https://github.com/robinje/ad-processor

  GitHubBranch:
    Description: Repo Branch.
    Type: String
    Default: develop

  S3BucketPrivate:
    Description: Location for Private Artifacts
    Type: String
    Default: dev-private

Resources:
  LambdaCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: Lambda
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: S3_BUCKET
            Type: PLAINTEXT
            Value: !Ref S3BucketPrivate
      Description: Packages the Lambdas
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/CodeBuildRole
      Source:
        Auth:
          Type: OAUTH
        BuildSpec: buildspec/lambda.yml
        Location: !Ref GitRepository
        Type: GITHUB
        GitCloneDepth: 1
      SourceVersion: !Ref GitHubBranch
      TimeoutInMinutes: 30
      Artifacts:
        Type: S3
        Location: !Ref S3BucketPrivate
        Path: /
        NamespaceType: NONE
        Packaging: NONE
        OverrideArtifactName: FALSE

  LambdaLayerCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: LambdaLayer
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
      Description: Packages the Lambda Layer
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/service-role/CodeBuildRole
      Source:
        Auth:
          Type: OAUTH
        BuildSpec: buildspec/layer.yml
        Location: !Ref GitRepository
        Type: GITHUB
        GitCloneDepth: 1
      SourceVersion: !Ref GitHubBranch
      TimeoutInMinutes: 30
      Artifacts:
        Type: S3
        Location: !Ref S3BucketPrivate
        Path: /
        NamespaceType: NONE
        Packaging: NONE
        OverrideArtifactName: FALSE