AWSTemplateFormatVersion: 2010-09-09

Description: Create the  Lambda Layer

Parameters:
  S3BucketPrivate:
    Description: Location for Private Artifacts
    Type: String
    Default: dev-private

Resources:
  Layer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.10
      CompatibleArchitectures:
        - x86_64
      Content:
        S3Bucket: !Ref S3BucketPrivate
        S3Key: LambdaLayer/ad-processor.zip
      Description: Lambda Dependencies
      LayerName: AdProcessor

Outputs:
  LayerArn:
    Description: ARN for the Lambda Layer
    Value: !Ref Layer