AWSTemplateFormatVersion: 2010-09-09

Description: Template for Deploying the Second Stage.

Parameters:
  S3BucketPrivate:
    Description: Location for Private Artifacts
    Type: String
    Default: dev-private

  TemplateLayer:
    Description: Path to Layer Template
    Type: String
    Default: layer.yml

  TemplateLambda:
    Description: Path to Lambda Template
    Type: String
    Default: lambda.yml

  Subnets:
    Description: Subnets for the Lambda
    Type: AWS::EC2::Subnet::Id

  VPC:
    Description: VPC for the Lambda
    Type: AWS::EC2::VPC::Id

  SNSTopic:
    Description: SNS Topic for the Lambda
    Type: String
    Default: ad-processor


Resources:
  ChildStackLayer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketPrivate}.s3.amazonaws.com/cf/${TemplateLayer}
      Parameters:
        S3BucketPrivate: !Ref S3BucketPrivate

  ChildStackLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketPrivate}.s3.amazonaws.com/cf/${TemplateLambda}
      Parameters:
        Layer: !GetAtt ChildStackLayer.Outputs.LayerArn
        S3BucketPrivate: !Ref S3BucketPrivate
        Subnets: !Ref Subnets
        VPC: !Ref VPC
        SNSTopic: !Ref SNSTopic
        
        